### ISSUE TITLE
Can not get duration before audio play

### ISSUE THREAD

**Issue by VCasecnikovs** [bluefireteam/audioplayers#1215] opened 2022-07-14 08:45 UTC
After setting the source I am trying to get the duration of the audio file. Unfortunately, the answer is zero.

The code:
```
    await player.setSource(event.source);
    var duration = await player.getDuration();
```

**Platforms**
OS: Windows & Android

**Comment by Gustl22** [comment] 2022-07-21 20:24
This cannot be guaranteed in all cases. The problem is e.g. for mp3 the duration is estimated which only will precisely work if playing the audio. But I didn't experience that on Android/Windows yet...

**Comment by tffajari** [comment] 2022-07-27 02:08
I have the same issue here, just_audio offer get duration before we play audio, but there is already to much code I implement using audio_player

**Comment by Gustl22** [comment] 2022-09-27 16:16
Closing in favor of #1033

**Closed by Gustl22** 2022-09-27 16:16 UTC
Labels: bug
