### ISSUE TITLE
App crashes when I play multiple sounds

### ISSUE THREAD

**Issue by Sherif-2001** [bluefireteam/audioplayers#1290] opened 2022-09-29 15:53 UTC
The app crashes when I play a bgm with sound effects and give me this error

D/AndroidRuntime(10672): Shutting down VM
E/AndroidRuntime(10672): FATAL EXCEPTION: main
E/AndroidRuntime(10672): Process: com.example.dino_game, PID: 10672
E/AndroidRuntime(10672): java.util.ConcurrentModificationException
E/AndroidRuntime(10672): 	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:757)
E/AndroidRuntime(10672): 	at java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:785)
E/AndroidRuntime(10672): 	at xyz.luan.audioplayers.AudioplayersPlugin$UpdateRunnable.run(AudioplayersPlugin.kt:212)
E/AndroidRuntime(10672): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(10672): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(10672): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(10672): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime(10672): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10672): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(10672): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/Process (10672): Sending signal. PID: 10672 SIG: 9
Lost connection to device.

## Audioplayers : 1.1.0

**Comment by spydon** [comment] 2022-10-03 19:40
Duplicate of https://github.com/bluefireteam/audioplayers/issues/1274

**Closed by spydon** 2022-10-03 19:40 UTC
Labels: bug
