### ISSUE TITLE
win7系统提示无法定位程序输入点mfplat.dll

### ISSUE THREAD

**Issue by zst1994** [bluefireteam/audioplayers#1239] opened 2022-08-10 08:09 UTC

**Comment by zst1994** [comment] 2022-08-10 08:12
![image](https://user-images.githubusercontent.com/31177280/183850379-2c597700-5bdd-4267-8253-74c0f85c6bcb.png)

**Comment by renancaraujo** [comment] 2022-08-11 11:48
Dupe of #1134

**Closed by renancaraujo** 2022-08-11 11:48 UTC
Labels: bug, wontfix
