### ISSUE TITLE
xyz.luan.audioplayers.player.MediaPlayerPlayer.isActuallyPlaying [Fatal Error] 

### ISSUE THREAD

**Issue by utkudenis** [bluefireteam/audioplayers#1229] opened 2022-07-29 15:31 UTC
Fatal Exception: java.lang.IllegalStateException
       at android.media.MediaPlayer.isPlaying(MediaPlayer.java)
       at xyz.luan.audioplayers.player.MediaPlayerPlayer.isActuallyPlaying(MediaPlayerPlayer.kt:35)
       at xyz.luan.audioplayers.player.WrappedPlayer.isActuallyPlaying(WrappedPlayer.kt:144)
       at xyz.luan.audioplayers.AudioplayersPlugin$UpdateCallback.run(AudioplayersPlugin.kt:209)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:101)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7529)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

this is the error log from firebase crashlytic. 
We migrated 0.20 to latest version 
flutter version 3.0.3 
platfrom android 

We didn't see this error on the tests both real devices and emulators but it according to crash report from play.console 
<img width="1108" alt="image" src="https://user-images.githubusercontent.com/68633376/181793383-8d0f02c0-6164-4e73-ba60-90fc23ecf8c6.png">

**Comment by spydon** [comment] 2022-08-08 19:06
Duplicate of #1150

**Closed by spydon** 2022-08-08 19:06 UTC
Labels: bug
