### ISSUE TITLE
Failed to install nuget package

### ISSUE THREAD

**Issue by lgLindstrom** [bluefireteam/audioplayers#1615] opened 2023-08-22 15:14 UTC
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

I get the following error message when building for Debug with VSCode

```
Argument cannot be null or empty
Parameternamn: primarySources
CMake Error at flutter/ephemeral/.plugin_symlinks/audioplayers_windows/windows/CMakeLists.txt:29 (message):
  Failed to install nuget package
  Microsoft.Windows.ImplementationLibrary.1.0.210803.1

Exception: Unable to generate build files
```

### Expected behaviour

Build without error

### Affected platforms

Windows

### AudioPlayers Version

^5.1.0

### Build mode

debug

### Related issues / more information

nuget in path,,,,   "../AppData/Local/Microsoft/WinGet/Links/nuget" 
installed Visual Studion 2022, community edition

### Working on PR

no way

**Comment by Gustl22** [comment] 2023-08-22 20:45
Did you try a `flutter clean` ?
Also search the existing (also closed) issues for help.

See Windows build requirements: https://github.com/bluefireteam/audioplayers/blob/main/packages/audioplayers_windows/README.md#setup-for-windows

**Comment by khomin** [comment] 2023-09-04 16:46
<img width="945" alt="Screen Shot 2023-09-04 at 8 45 53 PM" src="https://github.com/bluefireteam/audioplayers/assets/7860640/44b45fe0-48e2-4bcc-82f7-2f8a93672028">
Also have same problem

**Comment by aluedtke7** [comment] 2023-09-16 08:41
I have the exact same behaviour on Windows 10! 

On Windows 11 my code compiles without problems. @khomin : is your screenshot form Windows 10 or 11?

**Comment by khomin** [comment] 2023-09-16 09:07
> I have the exact same behaviour on Windows 10!
> 
> On Windows 11 my code compiles without problems. @khomin : is your screenshot form Windows 10 or 11?

Windows 10
I think the problem was in old dependencies

**Comment by aluedtke7** [comment] 2023-09-16 09:10
@khomin: if it works now on your win 10 machine: what did you change?

**Comment by khomin** [comment] 2023-09-16 09:49
> @khomin: if it works now on your win 10 machine: what did you change?

I did:
 1) actually it turned out i downgraded player:
     audioplayers: ^4.0.0
2) reinstalled visual studio

Now i tried '5.1.0' again
with flutter pub cache clean
and everything is working fine

I don't know what was that
Remember that sourceforce was off one day could it be the cause

Flutter 3.10.5

**Comment by Gustl22** [comment] 2023-09-26 10:43
I'm closing, as it may was a temporary failure.

**Closed by Gustl22** 2023-09-26 10:43 UTC
Labels: bug, platform-windows

**Comment by gokhanmeteerturk** [comment] 2024-01-10 18:54
I was having the same issue, but it didn't go away with flutter clean & get:

```bash
Argument cannot be null or empty
Parameter name: primarySources
CMake Error at flutter/ephemeral/.plugin_symlinks/audioplayers_windows/windows/CMakeLists.txt:29 (message):
  Failed to install nuget package
  Microsoft.Windows.ImplementationLibrary.1.0.210803.1
```

Having nuget in PATH has nothing to do with the problem. If that was the case, we would see this error:

> Nuget.exe not found, trying to download or use cached version.

Problem turned out to be just a misconfiguration.
I had this in %APPDATA%\NuGet\nuget.config :

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
  </packageSources>
</configuration>
```

So I changed it with this:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
</configuration>
```

This fixed the error, but I still couldn't build the application due to a bunch of other Visual Studio related issues. I had VS Build tools 2019. I installed 2022, along with "C++ ATL for latest vXXX build tools (x86 & x64)" (for flutter_secure_storage_windows_plugin to work) and then... It worked.

So if anyone experiences this issue, it is most probably a configuration issue with your windows development environment. Try the nuget.config fix first, if it doesn't work, directly uninstall or upgrade Visual Studio Build Tools.

**Comment by StrictlySkyler** [comment] 2024-08-28 02:30
> I was having the same issue, but it didn't go away with flutter clean & get:
> 
> ```shell
> Argument cannot be null or empty
> Parameter name: primarySources
> CMake Error at flutter/ephemeral/.plugin_symlinks/audioplayers_windows/windows/CMakeLists.txt:29 (message):
>   Failed to install nuget package
>   Microsoft.Windows.ImplementationLibrary.1.0.210803.1
> ```
> 
> Having nuget in PATH has nothing to do with the problem. If that was the case, we would see this error:
> 
> > Nuget.exe not found, trying to download or use cached version.
> 
> Problem turned out to be just a misconfiguration. I had this in %APPDATA%\NuGet\nuget.config :
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <configuration>
>   <packageSources>
>   </packageSources>
> </configuration>
> ```
> 
> So I changed it with this:
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <configuration>
>   <packageSources>
>     <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
>   </packageSources>
> </configuration>
> ```
> 
> This fixed the error, but I still couldn't build the application due to a bunch of other Visual Studio related issues. I had VS Build tools 2019. I installed 2022, along with "C++ ATL for latest vXXX build tools (x86 & x64)" (for flutter_secure_storage_windows_plugin to work) and then... It worked.
> 
> So if anyone experiences this issue, it is most probably a configuration issue with your windows development environment. Try the nuget.config fix first, if it doesn't work, directly uninstall or upgrade Visual Studio Build Tools.

This ultimately was the fix for me as well, thank you!

I'll also add that my `NuGet.config` looked like this beforehand:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageRestore>
    <add key="enabled" value="True" />
  </packageRestore>
  <bindingRedirects>
    <add key="skip" value="False" />
  </bindingRedirects>
  <packageManagement>
    <add key="disabled" value="False" />
  </packageManagement>
</configuration>
```
Adding the `<packageSources>` schema ultimately did the trick.
