### ISSUE TITLE
PlatformException on Android emulator (Pixel 5 API 32)

### ISSUE THREAD

**Issue by under3415** [bluefireteam/audioplayers#1201] opened 2022-07-03 00:37 UTC
Frequent `PlatformException` errors while running on Pixel 5 API 32 emulator

**Full Description**
While testing on the emulator, getting frequent `PlatofrmException` error. Was not getting these on Pixel 4 API 31 and physical device

**Code to Reproduce**
````
await _soundPlayer.play(
          AssetSource('sounds/my_sound.mp3'),
````

**Log Errors**

> PlatformException (PlatformException(Unexpected error!, null, java.lang.IllegalStateException
> 	at android.media.MediaPlayer._setVolume(Native Method)
> 	at android.media.MediaPlayer.playerSetVolume(MediaPlayer.java:2361)
> 	at android.media.PlayerBase.updatePlayerVolume(PlayerBase.java:240)
> 	at android.media.PlayerBase.baseSetVolume(PlayerBase.java:255)
> 	at android.media.MediaPlayer.setVolume(MediaPlayer.java:2356)
> 	at xyz.luan.audioplayers.player.MediaPlayerPlayer.setVolume(MediaPlayerPlayer.kt:39)
> 	at xyz.luan.audioplayers.player.WrappedPlayer.configAndPrepare(WrappedPlayer.kt:291)
> 	at xyz.luan.audioplayers.player.WrappedPlayer.setSource(WrappedPlayer.kt:30)
> 	at xyz.luan.audioplayers.AudioplayersPlugin.handler(AudioplayersPlugin.kt:87)
> 	at xyz.luan.audioplayers.AudioplayersPlugin.access$handler(AudioplayersPlugin.kt:23)
> 	at xyz.luan.audioplayers.AudioplayersPlugin$onAttachedToEngine$1$1.invoke(AudioplayersPlugin.kt:39)
> 	at xyz.luan.audioplayers.AudioplayersPlugin$onAttachedToEngine$1$1.invoke(AudioplayersPlugin.kt:39)
> 	at xyz.luan.audioplayers.AudioplayersPlugin$safeCall$1.invokeSuspend(AudioplayersPlugin.kt:58)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
> 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
> 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
> , null))

**Files/URLs/Sources**
N/A

**Screenshots**
N/A

**Platforms**
List in detail here **all** the platforms that you have tested, indicating which platforms the error occurs on. Please try to test on as many different platforms as possible to make our lives easier (this is optional). You must add at least one platform in which the problem occurs (evidently). For each platform listed, you must specify:

* OS: android,
* OS version: Pixel 5 API 32
* Device: Emullator
* audioplayers version: 1.0.1
* release or not release: Debug mode
* does the error occur and does it have any peculiarities: N/A

**Comment by AriDevC** [comment] 2022-07-09 16:57
This is indeed an annoying bug on android emulator, mine ends up crashing frequently at random times.

**Comment by spydon** [comment] 2022-08-08 19:08
Duplicate of #1150

**Closed by spydon** 2022-08-08 19:08 UTC
Labels: bug
