### ISSUE TITLE
java.lang.IllegalStateException

### ISSUE THREAD

**Issue by 14064635** [bluefireteam/audioplayers#1223] opened 2022-07-25 09:06 UTC
java.lang.IllegalStateException

解析原始
1
android.media.MediaPlayer.isPlaying(Native Method)
2
xyz.luan.audioplayers.player.MediaPlayerPlayer.isActuallyPlaying(MediaPlayerPlayer.kt:35)
3
xyz.luan.audioplayers.player.WrappedPlayer.isActuallyPlaying(WrappedPlayer.kt:144)
4
xyz.luan.audioplayers.AudioplayersPlugin$UpdateCallback.run(AudioplayersPlugin.kt:209)
5
android.os.Handler.handleCallback(Handler.java:938)
6
android.os.Handler.dispatchMessage(Handler.java:99)
7
android.os.Looper.loop(Looper.java:233)
8
android.app.ActivityThread.main(ActivityThread.java:8030)
9
java.lang.reflect.Method.invoke(Native Method)
10
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
11
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

**Comment by spydon** [comment] 2022-08-08 19:06
Duplicate of #1150

**Closed by spydon** 2022-08-08 19:06 UTC
Labels: bug
