### ISSUE TITLE
sound goes off when screen off or app minimised

### ISSUE THREAD

**Issue by pranavkapoorr** [bluefireteam/audioplayers#60] opened 2018-11-21 04:22 UTC
Hey guys my issue is that when I press the home button to send app in background(without terminating it) or lock screen, audio stops. On unlocking screen or on bring it to the front makes it play again. Any suggestions?

Thanks in advance :)

**Comment by luanpotter** [comment] 2018-11-24 10:47
Hi, @pranavkapoorr !

The sound should keep playing on background, unless you stop it yourself. AFAIK, that's the expected behavior, and works on my apps.

Maybe the problem is that you have created the instance of AP inside your Widget and it is getting disposed? Try to create it as a global variable and see if it makes any difference.

Also, this could be related to #36. Need to check into that as well.

**Comment by pranavkapoorr** [comment] 2018-11-25 04:45
Hi @luanpotter 

Thank you so much for your advise. I tried creating the global instance of audiocache, it worked on my ios simulator but on actual iphone, still sound stops on app minimisation or lock screen. :(

Pranav

**Comment by pranavkapoorr** [comment] 2018-11-30 04:46
Hi @luanpotter 

One more question. How to loop a sound clip without a pause at the end? Is there any way by which It can be done asynchronously so that when It seeks to start position, it doesn't pause?

thanks in advance for both the issues

pranav

**Comment by luanpotter** [comment] 2018-12-08 16:41
@pranavkapoorr , you can loop w/out pauses by using the ReleaseMode LOOP option. Regarding your other problem, I'm not sure what's causing it, I'll try to take a look later (right now I'm busy), but I don't know the reason up front. I hope someone else can help us out!

**Comment by benwicks** [comment] 2018-12-13 16:54
@pranavkapoorr I had the same problem and was able to resolve it via this change in #66

**Comment by pranavkapoorr** [comment] 2018-12-15 03:06
@benwicks yayy it fixed the issue. Thank you so much :)

cheers

**Comment by pranavkapoorr** [comment] 2018-12-15 03:19
@luanpotter I tried using ReleaseMode Loop, it does the same thing.... it creates a pause and then plays the sound from beginning....any idea to seamlessly seek it to start without pause??

**Comment by luanpotter** [comment] 2018-12-15 04:14
Fixed by #66, thanks @benwicks !

**Closed as completed** 2018-12-15 04:13 UTC
