### ISSUE TITLE
AudioPlayers Exception flutter web

### ISSUE THREAD

**Issue by ankarastrix** [bluefireteam/audioplayers#1596] opened 2023-08-07 13:27 UTC
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

Exception in Flutter web (only in release) (Chrome) platform:

### Expected behaviour

`AudioPlayers Exception: AudioPlayerException(	AssetSource(path: new_message.mp3),PlatformException(4, DEMUXER_ERROR_COULD_NOT_OPEN: FFmpegDemuxer: open context failed, null, null)`

### Steps to reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

### Code sample

<details>
<summary>Code sample</summary>

```dart
void main() {
}
```

</details>

### Affected platforms

web

### Platform details

Chrome Version 115.0.5790.170 (Official Build) (x86_64)

### AudioPlayers Version

5.0.0

### Logs

```
my relevant logs
```

<details>
  <summary>Full Logs</summary>

  

  ```
  my full logs or a link to a gist
  ```

  Flutter doctor:
  ```
  Output of: flutter doctor -v
  ```
</details>

### Working on PR

no way

**Comment by Gustl22** [comment] 2023-08-07 14:28
Can you provide the file for `new_message.mp3` or can you reproduce with our [example](https://github.com/bluefireteam/audioplayers/tree/main/packages/audioplayers/example)? Thx :)

**Comment by Gustl22** [comment] 2023-09-17 14:30
Closing as I cannot reproduce without the sources.

**Closed by Gustl22** 2023-09-17 14:30 UTC
Labels: bug, platform-web
