### ISSUE TITLE
Cannot run my app after installing audioplayers package

### ISSUE THREAD

**Issue by ricophie03** [bluefireteam/audioplayers#1409] opened 2023-01-29 05:08 UTC
I'm using android and i can't run my app after installing this package (version 3.0.1) on my dependencies. And your documentation is not helping at all to understand how to use the current version of this package. I like it better when it's on version 0.17.4, really easy to use and the documentation really helps.

**Comment by Gustl22** [comment] 2023-01-29 09:00
Did you follow the [Getting started](https://github.com/bluefireteam/audioplayers/blob/main/getting_started.md) guide?
Also you have to provide more information on what is not working, that would be nice. In order to help you properly you would need to fill the issue template :)

**Comment by Hussein-Kurhily** [comment] 2023-01-30 17:20
I have the same problem

**Comment by Gustl22** [comment] 2023-01-30 17:40
@Hussein-Kurhily so can you provide more information? Else we cannot help you!

**Comment by japostoles** [comment] 2023-01-31 17:58
I'm guessing the issue is the same one I'm receiving during build time after updating to 3.0.1:

```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
e: /home/jonathan/.pub-cache/hosted/pub.dartlang.org/audioplayers_android-1.1.1/android/src/main/kotlin/xyz/luan/audioplayers/AudioContext.kt: (11, 12): Redeclaration: AudioContextAndroid
e: /home/jonathan/.pub-cache/hosted/pub.dartlang.org/audioplayers_android-1.1.1/android/src/main/kotlin/xyz/luan/audioplayers/AudioplayersPlugin.kt: (23, 11): Redeclaration: FlutterHandler
e: /home/jonathan/.pub-cache/hosted/pub.dartlang.org/audioplayers_android-1.1.1/android/src/main/kotlin/xyz/luan/audioplayers/AudioplayersPlugin.kt: (25, 7): Redeclaration: AudioplayersPlugin
e: /home/jonathan/.pub-cache/hosted/pub.dartlang.org/audioplayers_android-1.1.1/android/src/main/kotlin/xyz/luan/audioplayers/AudioplayersPlugin.kt: (244, 19): Redeclaration: IUpdateCallback
e: /home/jonathan/.pub-cache/hosted/pub.dartlang.org/audioplayers_android-1.1.1/android/src/main/kotlin/xyz/luan/audioplayers/AudioplayersPlugin.kt: (251, 54): Overload resolution ambiguity:
public fun String.toConstantCase(): String defined in xyz.luan.audioplayers in file AudioplayersPlugin.kt

public fun String.toConstantCase(): String defined in xyz.luan.audioplayers in file AudioplayersPlugin.kt
e: /home/jonathan/.pub-cache/hosted/pub.dartlang.org/audioplayers_android-1.1.1/android/src/main/kotlin/xyz/luan/audioplayers/AudioplayersPlugin.kt: (254, 1): Conflicting overloads: public fun String.toConstantCase(): String defined in xyz.luan.audioplayers in file AudioplayersPlugin.kt, public fun String.toConstantCase(): String defined in xyz.luan.audioplayers in file AudioplayersPlugin.kt
e: /home/jonathan/.pub-cache/hosted/pub.dartlang.org/audioplayers_android-1.1.1/android/src/main/kotlin/xyz/luan/audioplayers/player/MediaPlayerPlayer.kt: (9, 7): Redeclaration: MediaPlayerPlayer
e: /home/jonathan/.pub-cache/hosted/pub.dartlang.org/audioplayers_android-1.1.1/android/src/main/kotlin/xyz/luan/audioplayers/player/SoundPoolPlayer.kt: (16, 7): Redeclaration: SoundPoolPlayer
e: /home/jonathan/.pub-cache/hosted/pub.dartlang.org/audioplayers_android-1.1.1/android/src/main/kotlin/xyz/luan/audioplayers/player/WrappedPlayer.kt: (17, 7): Redeclaration: WrappedPlayer
e: /home/jonathan/.pub-cache/hosted/pub.dartlang.org/audioplayers_android-2.0.0/android/src/main/kotlin/xyz/luan/audioplayers/AudioContext.kt: (12, 12): Redeclaration: AudioContextAndroid
e: /home/jonathan/.pub-cache/hosted/pub.dartlang.org/audioplayers_android-2.0.0/android/src/main/kotlin/xyz/luan/audioplayers/AudioContext.kt: (64, 35): Unresolved reference: audioMode

e: /home/jonathan/.pub-cache/hosted/pub.dartlang.org/audioplayers_android-2.0.0/android/src/main/kotlin/xyz/luan/audioplayers/AudioplayersPlugin.kt: (25, 11): Redeclaration: FlutterHandler
e: /home/jonathan/.pub-cache/hosted/pub.dartlang.org/audioplayers_android-2.0.0/android/src/main/kotlin/xyz/luan/audioplayers/AudioplayersPlugin.kt: (27, 7): Redeclaration: AudioplayersPlugin
e: /home/jonathan/.pub-cache/hosted/pub.dartlang.org/audioplayers_android-2.0.0/android/src/main/kotlin/xyz/luan/audioplayers/AudioplayersPlugin.kt: (27, 43): Cannot access 'IUpdateCallback': it is private in file
e: /home/jonathan/.pub-cache/hosted/pub.dartlang.org/audioplayers_android-2.0.0/android/src/main/kotlin/xyz/luan/audioplayers/AudioplayersPlugin.kt: (84, 57): Unresolved reference: audioMode
e: /home/jonathan/.pub-cache/hosted/pub.dartlang.org/audioplayers_android-2.0.0/android/src/main/kotlin/xyz/luan/audioplayers/AudioplayersPlugin.kt: (174, 71): Too many arguments for internal constructor WrappedPlayer(ref: AudioplayersPlugin, playerId: String, context: AudioContextAndroid) defined in xyz.luan.audioplayers.player.WrappedPlayer
e: /home/jonathan/.pub-cache/hosted/pub.dartlang.org/audioplayers_android-2.0.0/android/src/main/kotlin/xyz/luan/audioplayers/AudioplayersPlugin.kt: (210, 5): 'public open fun startUpdates(): Unit defined in xyz.luan.audioplayers.AudioplayersPlugin' has no access to 'public abstract fun startUpdates(): Unit defined in xyz.luan.audioplayers.IUpdateCallback', so it cannot override it
e: /home/jonathan/.pub-cache/hosted/pub.dartlang.org/audioplayers_android-2.0.0/android/src/main/kotlin/xyz/luan/audioplayers/AudioplayersPlugin.kt: (214, 5): 'public open fun stopUpdates(): Unit defined in xyz.luan.audioplayers.AudioplayersPlugin' has no access to 'public abstract fun stopUpdates(): Unit defined in xyz.luan.audioplayers.IUpdateCallback', so it cannot override it
e: /home/jonathan/.pub-cache/hosted/pub.dartlang.org/audioplayers_android-2.0.0/android/src/main/kotlin/xyz/luan/audioplayers/AudioplayersPlugin.kt: (222, 25): Cannot access 'IUpdateCallback': it is private in file

e: /home/jonathan/.pub-cache/hosted/pub.dartlang.org/audioplayers_android-2.0.0/android/src/main/kotlin/xyz/luan/audioplayers/AudioplayersPlugin.kt: (234, 79): Cannot access 'IUpdateCallback': it is private in file
e: /home/jonathan/.pub-cache/hosted/pub.dartlang.org/audioplayers_android-2.0.0/android/src/main/kotlin/xyz/luan/audioplayers/AudioplayersPlugin.kt: (234, 94): No method 'equals(Any?): Boolean' available
e: /home/jonathan/.pub-cache/hosted/pub.dartlang.org/audioplayers_android-2.0.0/android/src/main/kotlin/xyz/luan/audioplayers/AudioplayersPlugin.kt: (235, 33): Cannot access 'IUpdateCallback': it is private in file
e: /home/jonathan/.pub-cache/hosted/pub.dartlang.org/audioplayers_android-2.0.0/android/src/main/kotlin/xyz/luan/audioplayers/AudioplayersPlugin.kt: (253, 32): Cannot access 'IUpdateCallback': it is private in file
e: /home/jonathan/.pub-cache/hosted/pub.dartlang.org/audioplayers_android-2.0.0/android/src/main/kotlin/xyz/luan/audioplayers/AudioplayersPlugin.kt: (269, 19): Redeclaration: IUpdateCallback
e: /home/jonathan/.pub-cache/hosted/pub.dartlang.org/audioplayers_android-2.0.0/android/src/main/kotlin/xyz/luan/audioplayers/AudioplayersPlugin.kt: (276, 54): Overload resolution ambiguity:
public fun String.toConstantCase(): String defined in xyz.luan.audioplayers in file AudioplayersPlugin.kt
public fun String.toConstantCase(): String defined in xyz.luan.audioplayers in file AudioplayersPlugin.kt
e: /home/jonathan/.pub-cache/hosted/pub.dartlang.org/audioplayers_android-2.0.0/android/src/main/kotlin/xyz/luan/audioplayers/AudioplayersPlugin.kt: (279, 1): Conflicting overloads: public fun String.toConstantCase(): String defined in xyz.luan.audioplayers in file AudioplayersPlugin.kt, public fun String.toConstantCase(): String defined in xyz.luan.audioplayers in file AudioplayersPlugin.kt
e: /home/jonathan/.pub-cache/hosted/pub.dartlang.org/audioplayers_android-2.0.0/android/src/main/kotlin/xyz/luan/audioplayers/AudioplayersPlugin.kt: (286, 12): None of the following functions can be called with the arguments supplied:
public constructor AudioContextAndroid() defined in xyz.luan.audioplayers.AudioContextAndroid
public constructor AudioContextAndroid(isSpeakerphoneOn: Boolean, stayAwake: Boolean, contentType: Int, usageType: Int, audioFocus: Int?) defined in xyz.luan.audioplayers.AudioContextAndroid
e: /home/jonathan/.pub-cache/hosted/pub.dartlang.org/audioplayers_android-2.0.0/android/src/main/kotlin/xyz/luan/audioplayers/player/MediaPlayerPlayer.kt: (9, 7): Redeclaration: MediaPlayerPlayer

e: /home/jonathan/.pub-cache/hosted/pub.dartlang.org/audioplayers_android-2.0.0/android/src/main/kotlin/xyz/luan/audioplayers/player/SoundPoolPlayer.kt: (17, 7): Redeclaration: SoundPoolPlayer
e: /home/jonathan/.pub-cache/hosted/pub.dartlang.org/audioplayers_android-2.0.0/android/src/main/kotlin/xyz/luan/audioplayers/player/SoundPoolPlayer.kt: (105, 47): Cannot access 'wrappedPlayer': it is private in 'SoundPoolPlayer'
e: /home/jonathan/.pub-cache/hosted/pub.dartlang.org/audioplayers_android-2.0.0/android/src/main/kotlin/xyz/luan/audioplayers/player/SoundPoolPlayer.kt: (107, 42): Cannot access 'soundId': it is private in 'SoundPoolPlayer'
e: /home/jonathan/.pub-cache/hosted/pub.dartlang.org/audioplayers_android-2.0.0/android/src/main/kotlin/xyz/luan/audioplayers/player/SoundPoolPlayer.kt: (227, 52): Cannot access 'urlSource': it is private in 'SoundPoolPlayer'
e: /home/jonathan/.pub-cache/hosted/pub.dartlang.org/audioplayers_android-2.0.0/android/src/main/kotlin/xyz/luan/audioplayers/player/SoundPoolPlayer.kt: (229, 79): Cannot access 'soundId': it is private in 'SoundPoolPlayer'
e: /home/jonathan/.pub-cache/hosted/pub.dartlang.org/audioplayers_android-2.0.0/android/src/main/kotlin/xyz/luan/audioplayers/player/SoundPoolPlayer.kt: (235, 40): Cannot access 'wrappedPlayer': it is private in 'SoundPoolPlayer'
e: /home/jonathan/.pub-cache/hosted/pub.dartlang.org/audioplayers_android-2.0.0/android/src/main/kotlin/xyz/luan/audioplayers/player/SoundPoolPlayer.kt: (236, 44): Cannot access 'wrappedPlayer': it is private in 'SoundPoolPlayer'
e: /home/jonathan/.pub-cache/hosted/pub.dartlang.org/audioplayers_android-2.0.0/android/src/main/kotlin/xyz/luan/audioplayers/player/WrappedPlayer.kt: (17, 7): Redeclaration: WrappedPlayer

e: /home/jonathan/.pub-cache/hosted/pub.dartlang.org/audioplayers_android-2.0.0/android/src/main/kotlin/xyz/luan/audioplayers/player/WrappedPlayer.kt: (128, 37): Unresolved reference: audioMode
e: /home/jonathan/.pub-cache/hosted/pub.dartlang.org/audioplayers_android-2.0.0/android/src/main/kotlin/xyz/luan/audioplayers/player/WrappedPlayer.kt: (167, 21): Unresolved reference: getAudioManager
e: /home/jonathan/.pub-cache/hosted/pub.dartlang.org/audioplayers_android-2.0.0/android/src/main/kotlin/xyz/luan/audioplayers/player/WrappedPlayer.kt: (305, 50): Too many arguments for public constructor SoundPoolPlayer(wrappedPlayer: WrappedPlayer) defined in xyz.luan.audioplayers.player.SoundPoolPlayer

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':audioplayers_android:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```

**Comment by Hussein-Kurhily** [comment] 2023-02-02 10:29
@Gustl22  
I am trying to add Audio from Assets folder 
but when I add an object 'player'  from AudioCache class like that 
AudioCache player =AudioCache(prefix: 'assets/number_eight_sound.mp3');

so when i write player. to use play method ->  i don't have any method (i mean i don't have the play method )

**Comment by jodymac** [comment] 2023-02-03 21:54
Running flutter clean / flutter pub get solved it for me also.

**Comment by spydon** [comment] 2023-02-10 09:02
> @Gustl22 I am trying to add Audio from Assets folder but when I add an object 'player' from AudioCache class like that AudioCache player =AudioCache(prefix: 'assets/number_eight_sound.mp3');
> 
> so when i write player. to use play method -> i don't have any method (i mean i don't have the play method )

This is unrelated to this issue.
You are setting the path prefix for the cache to be your asset directly, the prefix is a prefix that will be automatically added to paths that are added to the cache.
See [Getting Started](https://github.com/bluefireteam/audioplayers/blob/main/getting_started.md) guide for how to use the `AudioPlayer` class which most likely is the one you are looking for.

> This was solved for me by doing a flutter clean / flutter pub get

Glad that `flutter clean / flutter pub get` solved the issue, I'll close it as complete then. :)

**Closed by spydon** 2023-02-10 09:02 UTC
Labels: bug, changes-requested

**Comment by divyanshuk10** [comment] 2023-02-22 13:38
if anyone else comes across and find this for version = `audioplayers: ^3.0.1`. Also `assets_note1.wav` is directly pasted into assets folder.
```
onPressed: () {
                final player = AudioPlayer();
                player.play(AssetSource('assets_note1.wav'));
              }
```
