### ISSUE TITLE
setPlaybackRate and getCurrentPosition/Duration

### ISSUE THREAD

**Issue by dvorapa** [bluefireteam/audioplayers#512] opened 2020-04-30 20:02 UTC
Hi, I'm dealing with the following issue:

When I call setPlaybackRate (e.g. increase it to 110 %), I want to update also position and duration state variables having the prolonged/shortened time value (e.g. 1:05 of 2:20). audioplayers serve in streams only unchanged values (1:20 of 2:45) and the streams don't get updated when rate is changed.

So I looked for a way to manually call the streams to get updated (to the unchanged value). I found  getCurrentPosition and getDuration. But I have several issues with them, so I'm stuck:

- from the docs it is not clear, how to use them. If I call them, will they only call onAudioPositionChanged and onDurationChanged streams and finish with int = status code? Or will they ask for current duration and position and return it? For a status code they return sometimes too high value (like 45350)
- If I call getDuration/getCurrentPosition, it sometimes makes my player skip to the next song. Either getDuration produces incorrect (too short) duration, or it makes the duration and status code swap places (returns 45350 as a status code), or it somehow sets the current track as finished. I also get errors like this to console:
```
E/flutter (31015): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Unsupported value: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.media.MediaPlayer.getCurrentPosition()' on a null object reference, null)
E/flutter (31015): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569)
E/flutter (31015): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321)
E/flutter (31015): <asynchronous suspension>
E/flutter (31015): #2      AudioPlayer._invokeMethod (package:audioplayers/audioplayers.dart:319)
E/flutter (31015): #3      AudioPlayer.getCurrentPosition (package:audioplayers/audioplayers.dart:533)
E/flutter (31015): #4      _PlayerState.onRate (package:stepslow/main.dart:532)
E/flutter (31015): <asynchronous suspension>
E/flutter (31015): #5      _PlayerState.onPlay (package:stepslow/main.dart:296)
E/flutter (31015): #6      _PlayerState._changeState (package:stepslow/main.dart:538)
E/flutter (31015): #7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706)
E/flutter (31015): #8      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789)
E/flutter (31015): #9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182)
E/flutter (31015): #10     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486)
E/flutter (31015): #11     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282)
E/flutter (31015): #12     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:236)
E/flutter (31015): #13     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156)
E/flutter (31015): #14     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222)
E/flutter (31015): #15     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198)
E/flutter (31015): #16     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156)
E/flutter (31015): #17     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102)
E/flutter (31015): #18     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86)
E/flutter (31015): #19     _rootRunUnary (dart:async/zone.dart:1138)
E/flutter (31015): #20     _CustomZone.runUnary (dart:async/zone.dart:1031)
E/flutter (31015): #21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
E/flutter (31015): #22     _invoke1 (dart:ui/hooks.dart:273)
E/flutter (31015): #23     _dispatchPointerDataPacket (dart:ui/hooks.dart:182)
```

**Comment by dvorapa** [comment] 2020-05-14 12:00
Might also be solved with https://github.com/luanpotter/audioplayers/issues/385

**Comment by luanpotter** [comment] 2021-04-14 14:16
Ok, let's try to divide this into bits:

> When I call setPlaybackRate (e.g. increase it to 110 %), I want to update also position and duration state variables having the prolonged/shortened time value (e.g. 1:05 of 2:20)

You can just divide the times by the playback rate

> I found getCurrentPosition and getDuration

Those should work!

>  If I call them, will they only call onAudioPositionChanged and onDurationChanged streams and finish with int = status code?

I don't quite understand this question... there are examples on the readme on how to use:

```
  player.onAudioPositionChanged.listen((Duration  p) => {
    print('Current position: $p');
    setState(() => position = p);
  });
```

that should give you all info you want, and you can divide by the playbackRate if that is what you want.

---

It seems, if I understand correctly, this has nothing to do with playbackrate right? You are just reporting some bugs related to onAudioPositionChanged and onDurationChanged?

if so, should we open more specific issues for each bug, with code samples, expected behaviour and actual behaviour?

for example:

> If I call getDuration/getCurrentPosition, it sometimes makes my player skip to the next song.

that would definitely be a bug

> Unhandled Exception: PlatformException(error, Unsupported value: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.media.MediaPlayer.getCurrentPosition()' on a null object reference, null)

definitely a bug

etc.

with the code examples we can easily run and repro to figure out what is going on. also need to know the platform, etc (we should have a template or guide somewhere).

**Comment by dvorapa** [comment] 2021-04-14 20:14
Sorry, I completely forgot about this. You are right, I tried to describe issue with getCurrentPosition and getDuration. For example if I called getCurrentPosition and seeked to its result, it threw me an _impossible seek_ error. getCurrentPosition's result dramatically differred for me from what onAudioPositionChanged gave. You can easily compare this behavior like this:

```
    audioPlayer.onDurationChanged.listen((Duration d) {
      int getd = audioPlayer.getDuration();
      print('$d $getd');
    });
    audioPlayer.onAudioPositionChanged.listen((Duration p) {
      int getp = audioPlayer.getCurrentPosition();
      print('$p $getp');
    });
```
(there might be some await needed and some Duration -> int conversion too, I'm writing this without looking)

p is changing constantly every second (at least). getp does not. It is still the same throughout the playback. d and getd do not match. Even after some ms -> s -> min -> h conversions they do not match. Both of these should be investigated. In my project I avoided those two methods, My workaround works for me well. Feel free to close this if you can not reproduce any of this (it might get fixed since I reported it a year ago). I can not test this currently, not at my personal pc.

**Comment by Gustl22** [comment] 2022-09-03 10:00
Since this is quite old, and we added bunch of fixes to the android platform in e.g. #1247 and also provide tests, I'm closing this. Feel free to open a new report, if it's still a thing :)

**Closed by Gustl22** 2022-09-03 10:00 UTC
Labels: bug, platform-android
