### ISSUE TITLE
Exception has occurred. PlatformException (PlatformException(DarwinAudioError, AVPlayerItem.Status.failed on setSourceUrl, null, null))

### ISSUE THREAD

**Issue by Afife21** [bluefireteam/audioplayers#1473] opened 2023-04-13 00:06 UTC
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

When I try to play an url from firebase storage on android devices are working but ios does not. 
Gettting this error ; Exception has occurred.
PlatformException (PlatformException(DarwinAudioError, AVPlayerItem.Status.failed on setSourceUrl, null, null))

### Steps to reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

### Code sample

<details>
<summary>Code sample</summary>

```dart
void main() {
}
```

</details>

### Affected platforms

iOS

### AudioPlayers Version

^4.0.1

### Logs

```
my relevant logs
```

<details>
  <summary>Full Logs</summary>

  

  ```
  my full logs or a link to a gist
  ```

  Flutter doctor:
  ```
  Output of: flutter doctor -v
  ```
</details>

### Working on PR

no way

**Comment by Gustl22** [comment] 2023-04-24 12:44
Plz fill the issue form as detailed as possible. E.g. what resource / file did you play? Otherwise we cannot help. Probably your file is not supported on iOS.

**Comment by eli1stark** [comment] 2023-04-30 03:41
@Gustl22 This is started to reproduce with new major version 4.0. I don't have reproducible steps yet, it is logged in Crashlytics for me. And we can rule out "file is not supported", since it worked fine before v4.

**Comment by Gustl22** [comment] 2023-05-07 13:24
@Afife21 @eli1stark Sorry without concrete reproduction steps, we cannot help.
Also some user could have played an unsupported file format maybe, which wasn't the case before.

If you're sure and have more information feel free to open again or create a new issue with detailed steps and the file source. Hope you understand, Thx:)

Closing in favor of #1494

**Closed by Gustl22** 2023-05-07 13:24 UTC
Labels: bug, waiting for report, platform-ios
