### ISSUE TITLE
Crash MediaPlayer.isPlaying

### ISSUE THREAD

**Issue by lidaweicn** [bluefireteam/audioplayers#1212] opened 2022-07-12 02:31 UTC
Often crash during audio play

Anywhere there's audio playing, sometimes it crash, not every time
`
audioPlayer.play(UrlSource("..."))  or  audioPlayer.setSourceUrl("...")
`

D/AndroidRuntime(28965): Shutting down VM
E/AndroidRuntime(28965): FATAL EXCEPTION: main
E/AndroidRuntime(28965): Process: xxxxxx, PID: 28965
E/AndroidRuntime(28965): java.lang.IllegalStateException
E/AndroidRuntime(28965):        at android.media.MediaPlayer.isPlaying(Native Method)
E/AndroidRuntime(28965):        at xyz.luan.audioplayers.player.MediaPlayerPlayer.isActuallyPlaying(MediaPlayerPlayer.kt:35)
E/AndroidRuntime(28965):        at xyz.luan.audioplayers.player.WrappedPlayer.isActuallyPlaying(WrappedPlayer.kt:144)
E/AndroidRuntime(28965):        at xyz.luan.audioplayers.AudioplayersPlugin$UpdateCallback.run(AudioplayersPlugin.kt:209)
E/AndroidRuntime(28965):        at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(28965):        at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(28965):        at android.os.Looper.loop(Looper.java:224)
E/AndroidRuntime(28965):        at android.app.ActivityThread.main(ActivityThread.java:7562)
E/AndroidRuntime(28965):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(28965):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/AndroidRuntime(28965):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
I/Process (28965): Sending signal. PID: 28965 SIG: 9
Lost connection to device.

**Platforms**
* OS: android 10.
* Device:  physical device Mi MIX 3.
* flutter version:  2.10.5.
* audioplayers version: ^1.0.0.

**Comment by spydon** [comment] 2022-08-08 19:07
Duplicate of #1150

**Closed by spydon** 2022-08-08 19:07 UTC
Labels: bug
