### ISSUE TITLE
AudioPlayer plays sound through ear speaker on iPhone

### ISSUE THREAD

**Issue by Tobi696** [bluefireteam/audioplayers#1288] opened 2022-09-27 18:12 UTC

**Comment by Gustl22** [comment] 2022-09-27 21:21
Please file the issue template. We are not having a chance to reproduce the issue. Although we don't have the resources at the moment to handle ios bugs :/

**Comment by spydon** [comment] 2022-10-03 19:40
Duplicate of https://github.com/bluefireteam/audioplayers/issues/1194

**Closed by spydon** 2022-10-03 19:40 UTC
Labels: bug, changes-requested, platform-ios
