### ISSUE TITLE
502 from server: Bad Gateway

### ISSUE THREAD

**Issue by himanshu64** [bluefireteam/audioplayers#1037] opened 2021-12-01 08:07 UTC
**FAILURE: Build failed with an exception.

What went wrong:
Could not determine the dependencies of task ':app:processDebugResources'.
Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
Could not resolve androidx.core:core-ktx:+.
Required by:
project :app > project :audioplayers
> Failed to list versions for androidx.core:core-ktx.
> Unable to load Maven meta-data from https://google.bintray.com/exoplayer/androidx/core/core-ktx/maven-metadata.xml.
> Could not get resource 'https://google.bintray.com/exoplayer/androidx/core/core-ktx/maven-metadata.xml'.
> Could not GET 'https://google.bintray.com/exoplayer/androidx/core/core-ktx/maven-metadata.xml'. Received status code 502 from server: Bad Gateway**

Flutter 1.22.6 • channel unknown • unknown source
Framework • revision 9b2d32b605 (10 months ago) • 2021-01-22 14:36:39 -0800
Engine • revision 2f0af37152
Tools • Dart 2.10.5
environment:
  sdk: ">=2.6.0 <3.0.0"

audioplayers version: audioplayers: ^0.17.3

**Comment by spydon** [comment] 2021-12-01 10:02
Duplicate of #1036

**Closed by spydon** 2021-12-01 10:02 UTC
Labels: bug
